In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
tasks = [ 'Ate', 'Car', 'Eff', 'Inf', 'Mas', 'Nod', 'Pne',
                        'Pnt', 'Con', 'Ede', 'Emp', 'Fib', 'Ple', 
                        'Her', 'Nor', 'Cov']

In [150]:
idx = tasks.index('Pnt')
idx

7

In [84]:
rho_df = pd.read_csv('chexphoto/test_results/chexphoto0_7_13_14_r:1_baseline-lr:0.001-wd:0.0_still-galaxy-142_last.csv')
grad_df = pd.read_csv('heatmaps/csvfiles/grad_cam/ols_0_7_13_14_r:1_baseline-lr:0.001-wd:0.0_still-galaxy-142.csv')
norm_df = pd.read_csv('heatmaps/csvfiles/grad_norm_sq/ols_0_7_13_14_r:1_baseline-lr:0.001-wd:0.0_still-galaxy-142.csv')

In [85]:

prefix = '1_COVID-19/'
rho_df['image_name'] = rho_df['image_name'].str.replace(prefix, '', regex=False)

rho_df

,rho_14_0,rho_14_7,rho_14_13,rho_14_14,image_name,cosine_sim,sal_diff_norm,SmoothHR_Score_0.4,SmoothLR_Score_0.4,SmoothHR_Score_0.5,...,SmoothSqHR_Score_0.55,SmoothSqLR_Score_0.55,SmoothSqHR_Score_0.6,SmoothSqLR_Score_0.6,SmoothSqHR_Score_0.65,SmoothSqLR_Score_0.65,SmoothSqHR_Score_0.7,SmoothSqLR_Score_0.7,SmoothSqHR_Score_0.75,SmoothSqLR_Score_0.75
0,-0.119622,0.073421,0.084966,1.0,MIDRC-RICORD-1C-419639-000484-56426-0.png,0.747446,3.838806,0.284615,0.211027,0.146341,...,0.500000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000,0.000000
1,-0.238786,0.012182,-0.123019,1.0,COVID-2009.png,0.824941,2.859974,0.748092,0.635294,0.766667,...,0.916667,0.363636,1.000000,0.333333,1.000000,0.000000,1.000000,0.000000,1.000,0.000000
2,0.196930,0.035369,-0.131642,1.0,COVID-3168.png,0.857569,2.496254,0.719512,0.785714,0.884615,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000,1.000000
3,-0.143183,-0.080474,-0.135176,1.0,COVID-3447.png,0.838083,2.836977,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
4,0.179407,0.032751,0.245709,1.0,COVID-2928.png,0.850696,2.219031,0.093750,0.028571,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,-0.227934,-0.107422,-0.085989,1.0,COVID-2090.png,0.832970,2.685337,0.287671,0.231884,0.229167,...,0.041667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
4808,0.135740,-0.089537,-0.104369,1.0,COVID-3413.png,0.852972,2.792071,0.358696,0.342105,0.311111,...,0.000000,0.294118,0.000000,0.230769,0.000000,0.300000,0.000000,0.142857,0.000,0.166667
4809,0.227081,0.038772,-0.034372,1.0,COVID-2133.png,0.838586,2.858364,0.566265,0.431925,0.584270,...,0.750000,0.361111,0.740741,0.370370,0.684211,0.411765,0.666667,0.636364,0.625,0.666667
4810,0.114282,0.035220,0.126806,1.0,MIDRC-RICORD-1C-419639-000906-51788-0.png,0.767137,4.110178,0.291367,0.328302,0.348214,...,0.000000,0.736842,0.000000,0.692308,0.000000,0.666667,0.000000,0.571429,0.000,0.333333
4811,0.134318,-0.035386,-0.078973,1.0,COVID-2826.png,0.874410,2.309135,0.287879,0.217213,0.277228,...,0.333333,0.235294,0.333333,0.272727,0.500000,0.300000,1.000000,0.250000,1.000,0.333333

In [86]:
grad_df = grad_df.drop(columns=['Unnamed: 0'])
norm_df = norm_df.drop(columns=['Unnamed: 0'])

In [87]:
#rename columns
grad_df = grad_df.rename(columns={"Image_Name": "image_name"})
norm_df = norm_df.rename(columns={"Image_Name": "image_name"})

In [88]:
grad_combine = pd.merge(grad_df, norm_df, on='image_name',how='outer',suffixes=('_grad', '_norm'))
final_df = pd.merge(rho_df, grad_combine, on='image_name',how='outer')

In [89]:
final_df

,rho_14_0,rho_14_7,rho_14_13,rho_14_14,image_name,cosine_sim,sal_diff_norm,SmoothHR_Score_0.4,SmoothLR_Score_0.4,SmoothHR_Score_0.5,...,HR_Score_0.55_norm,LR_Score_0.55_norm,HR_Score_0.6_norm,LR_Score_0.6_norm,HR_Score_0.65_norm,LR_Score_0.65_norm,HR_Score_0.7_norm,LR_Score_0.7_norm,HR_Score_0.75_norm,LR_Score_0.75_norm
0,-0.119622,0.073421,0.084966,1.0,MIDRC-RICORD-1C-419639-000484-56426-0.png,0.747446,3.838806,0.284615,0.211027,0.146341,...,0.400000,0.071429,0.444444,0.000000,0.363636,0.000000,0.500000,0.000000,0.000000,0.000000
1,-0.238786,0.012182,-0.123019,1.0,COVID-2009.png,0.824941,2.859974,0.748092,0.635294,0.766667,...,0.242424,0.235294,0.172414,0.242424,0.148148,0.200000,0.160000,0.148148,0.095238,0.166667
2,0.196930,0.035369,-0.131642,1.0,COVID-3168.png,0.857569,2.496254,0.719512,0.785714,0.884615,...,0.272727,0.333333,0.428571,0.428571,0.500000,0.500000,0.500000,0.500000,0.600000,0.666667
3,-0.143183,-0.080474,-0.135176,1.0,COVID-3447.png,0.838083,2.836977,0.000000,0.000000,0.000000,...,0.975000,0.977273,1.000000,0.975000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,0.179407,0.032751,0.245709,1.0,COVID-2928.png,0.850696,2.219031,0.093750,0.028571,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,-0.227934,-0.107422,-0.085989,1.0,COVID-2090.png,0.832970,2.685337,0.287671,0.231884,0.229167,...,0.687500,0.681818,0.600000,0.650000,0.571429,0.692308,0.750000,0.700000,1.000000,0.666667
4808,0.135740,-0.089537,-0.104369,1.0,COVID-3413.png,0.852972,2.792071,0.358696,0.342105,0.311111,...,0.437500,0.583333,0.416667,0.625000,0.166667,0.400000,0.000000,0.666667,0.000000,0.500000
4809,0.227081,0.038772,-0.034372,1.0,COVID-2133.png,0.838586,2.858364,0.566265,0.431925,0.584270,...,0.736842,0.642857,0.833333,0.750000,0.909091,0.777778,0.888889,0.857143,0.875000,0.857143
4810,0.114282,0.035220,0.126806,1.0,MIDRC-RICORD-1C-419639-000906-51788-0.png,0.767137,4.110178,0.291367,0.328302,0.348214,...,0.684211,0.666667,0.666667,0.625000,0.615385,0.545455,0.545455,0.600000,0.500000,0.428571
4811,0.134318,-0.035386,-0.078973,1.0,COVID-2826.png,0.874410,2.309135,0.287879,0.217213,0.277228,...,0.700000,0.625000,1.000000,0.833333,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [90]:
#write to csv
final_df.to_csv('final_csv/chexphoto/0_7_13_14.csv', index=False)