In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
tasks = [ 'Ate', 'Car', 'Eff', 'Inf', 'Mas', 'Nod', 'Pne',
                        'Pnt', 'Con', 'Ede', 'Emp', 'Fib', 'Ple', 
                        'Her', 'Nor', 'Cov']

In [150]:
idx = tasks.index('Pnt')
idx

7

In [84]:
rho_df = pd.read_csv('chexphoto/test_results/chexphoto0_7_13_14_r:1_baseline-lr:0.001-wd:0.0_still-galaxy-142_last.csv')
grad_df = pd.read_csv('heatmaps/csvfiles/grad_cam/ols_0_7_13_14_r:1_baseline-lr:0.001-wd:0.0_still-galaxy-142.csv')
norm_df = pd.read_csv('heatmaps/csvfiles/grad_norm_sq/ols_0_7_13_14_r:1_baseline-lr:0.001-wd:0.0_still-galaxy-142.csv')

In [85]:

prefix = '1_COVID-19/'
rho_df['image_name'] = rho_df['image_name'].str.replace(prefix, '', regex=False)

rho_df

,rho_14_0,rho_14_7,rho_14_13,rho_14_14,image_name,cosine_sim,sal_diff_norm,SmoothHR_Score_0.4,SmoothLR_Score_0.4,SmoothHR_Score_0.5,...,SmoothSqHR_Score_0.55,SmoothSqLR_Score_0.55,SmoothSqHR_Score_0.6,SmoothSqLR_Score_0.6,SmoothSqHR_Score_0.65,SmoothSqLR_Score_0.65,SmoothSqHR_Score_0.7,SmoothSqLR_Score_0.7,SmoothSqHR_Score_0.75,SmoothSqLR_Score_0.75
0,-0.119622,0.073421,0.084966,1.0,MIDRC-RICORD-1C-419639-000484-56426-0.png,0.747446,3.838806,0.284615,0.211027,0.146341,...,0.500000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000,0.000000
1,-0.238786,0.012182,-0.123019,1.0,COVID-2009.png,0.824941,2.859974,0.748092,0.635294,0.766667,...,0.916667,0.363636,1.000000,0.333333,1.000000,0.000000,1.000000,0.000000,1.000,0.000000
2,0.196930,0.035369,-0.131642,1.0,COVID-3168.png,0.857569,2.496254,0.719512,0.785714,0.884615,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000,1.000000
3,-0.143183,-0.080474,-0.135176,1.0,COVID-3447.png,0.838083,2.836977,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
4,0.179407,0.032751,0.245709,1.0,COVID-2928.png,0.850696,2.219031,0.093750,0.028571,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,-0.227934,-0.107422,-0.085989,1.0,COVID-2090.png,0.832970,2.685337,0.287671,0.231884,0.229167,...,0.041667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
4808,0.135740,-0.089537,-0.104369,1.0,COVID-3413.png,0.852972,2.792071,0.358696,0.342105,0.311111,...,0.000000,0.294118,0.000000,0.230769,0.000000,0.300000,0.000000,0.142857,0.000,0.166667
4809,0.227081,0.038772,-0.034372,1.0,COVID-2133.png,0.838586,2.858364,0.566265,0.431925,0.584270,...,0.750000,0.361111,0.740741,0.370370,0.684211,0.411765,0.666667,0.636364,0.625,0.666667
4810,0.114282,0.035220,0.126806,1.0,MIDRC-RICORD-1C-419639-000906-51788-0.png,0.767137,4.110178,0.291367,0.328302,0.348214,...,0.000000,0.736842,0.000000,0.692308,0.000000,0.666667,0.000000,0.571429,0.000,0.333333
4811,0.134318,-0.035386,-0.078973,1.0,COVID-2826.png,0.874410,2.309135,0.287879,0.217213,0.277228,...,0.333333,0.235294,0.333333,0.272727,0.500000,0.300000,1.000000,0.250000,1.000,0.333333

In [86]:
grad_df = grad_df.drop(columns=['Unnamed: 0'])
norm_df = norm_df.drop(columns=['Unnamed: 0'])

In [87]:
#rename columns
grad_df = grad_df.rename(columns={"Image_Name": "image_name"})
norm_df = norm_df.rename(columns={"Image_Name": "image_name"})

In [88]:
grad_combine = pd.merge(grad_df, norm_df, on='image_name',how='outer',suffixes=('_grad', '_norm'))
final_df = pd.merge(rho_df, grad_combine, on='image_name',how='outer')

In [89]:
final_df

,rho_14_0,rho_14_7,rho_14_13,rho_14_14,image_name,cosine_sim,sal_diff_norm,SmoothHR_Score_0.4,SmoothLR_Score_0.4,SmoothHR_Score_0.5,...,HR_Score_0.55_norm,LR_Score_0.55_norm,HR_Score_0.6_norm,LR_Score_0.6_norm,HR_Score_0.65_norm,LR_Score_0.65_norm,HR_Score_0.7_norm,LR_Score_0.7_norm,HR_Score_0.75_norm,LR_Score_0.75_norm
0,-0.119622,0.073421,0.084966,1.0,MIDRC-RICORD-1C-419639-000484-56426-0.png,0.747446,3.838806,0.284615,0.211027,0.146341,...,0.400000,0.071429,0.444444,0.000000,0.363636,0.000000,0.500000,0.000000,0.000000,0.000000
1,-0.238786,0.012182,-0.123019,1.0,COVID-2009.png,0.824941,2.859974,0.748092,0.635294,0.766667,...,0.242424,0.235294,0.172414,0.242424,0.148148,0.200000,0.160000,0.148148,0.095238,0.166667
2,0.196930,0.035369,-0.131642,1.0,COVID-3168.png,0.857569,2.496254,0.719512,0.785714,0.884615,...,0.272727,0.333333,0.428571,0.428571,0.500000,0.500000,0.500000,0.500000,0.600000,0.666667
3,-0.143183,-0.080474,-0.135176,1.0,COVID-3447.png,0.838083,2.836977,0.000000,0.000000,0.000000,...,0.975000,0.977273,1.000000,0.975000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,0.179407,0.032751,0.245709,1.0,COVID-2928.png,0.850696,2.219031,0.093750,0.028571,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,-0.227934,-0.107422,-0.085989,1.0,COVID-2090.png,0.832970,2.685337,0.287671,0.231884,0.229167,...,0.687500,0.681818,0.600000,0.650000,0.571429,0.692308,0.750000,0.700000,1.000000,0.666667
4808,0.135740,-0.089537,-0.104369,1.0,COVID-3413.png,0.852972,2.792071,0.358696,0.342105,0.311111,...,0.437500,0.583333,0.416667,0.625000,0.166667,0.400000,0.000000,0.666667,0.000000,0.500000
4809,0.227081,0.038772,-0.034372,1.0,COVID-2133.png,0.838586,2.858364,0.566265,0.431925,0.584270,...,0.736842,0.642857,0.833333,0.750000,0.909091,0.777778,0.888889,0.857143,0.875000,0.857143
4810,0.114282,0.035220,0.126806,1.0,MIDRC-RICORD-1C-419639-000906-51788-0.png,0.767137,4.110178,0.291367,0.328302,0.348214,...,0.684211,0.666667,0.666667,0.625000,0.615385,0.545455,0.545455,0.600000,0.500000,0.428571
4811,0.134318,-0.035386,-0.078973,1.0,COVID-2826.png,0.874410,2.309135,0.287879,0.217213,0.277228,...,0.700000,0.625000,1.000000,0.833333,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [90]:
#write to csv
final_df.to_csv('final_csv/chexphoto/0_7_13_14.csv', index=False)

In [42]:
!ls /data6/rajivporana_scratch/vindr_data/wh_proper_train > files.txt

In [43]:
#read files in a list
with open('files.txt') as f:
    files = f.readlines()

In [44]:
#remove whitespace characters like `\n` at the end of each line and remove .png and .jpeg chars

files = [x.strip() for x in files]
files = [x.replace('.png', '') for x in files]
files = [x.replace('.jpeg', '') for x in files]

In [49]:
for i in range(len(files)):
    files[i] = files[i].replace('png_train_', '', 1)

In [50]:
files

['000434271f63a053c4128a0ba6352c7f',
 '0005e8e3701dfb1dd93d53e2ff537b6e',
 '0007d316f756b3fa0baea2ff514ce945',
 '000ae00eb3942d27e0b97903dd563a6e',
 '00150343289f317a0ad5629d5b7d9ef9',
 '001d127bad87592efe45a5c7678f8b8d',
 '0021df30f3fddef551eb3df4354b1d06',
 '00291f7aff0123ea76a59998effef229',
 '003cfe5ce5c0ec5163138eb3b740e328',
 '004d2bc2111d639f5e8441ced52d55cb',
 '004dc2a50591fb5f1aaf012bffa95fd9',
 '0059d21bef1793fa9522e4ec8cae1a1a',
 '005be26a68485912e007a3703f43d60a',
 '005d70155f949c7785671800f2c8e1ca',
 '006e2726c6aa72f042a08b1406c39d52',
 '006e5626f560c1a2a74f953d71f16c11',
 '0071fbed56e53f6bfe416b7558b31f98',
 '0076d6a1e3139927fd62459c54276c3c',
 '007a5b30bc5eadb13017059543e0b6be',
 '008b3176a7248a0a189b5731ac8d2e95',
 '00948e3e6acc03044af454fb9700ca60',
 '009d4c31ebf87e51c5c8c160a4bd8006',
 '009fc6795a7be2faa76c6e1005edc418',
 '00a7e1e81b2122e5a0f298155573e549',
 '00a9f697d85a506d5b281f588addce4e',
 '00ad02393a5d0bd1e0dcf3196433499f',
 '00b05e693202bb65a0c0ca7a0201495d',
 '00bcb82818ea83d6a86df241762cd7d0',
 '00bedb314b716e802e72799b17edb059',
 '00c4051383149d0dbe166f38b67c9b52',
 '00e25f831ccd21bd41b558cfccbf1be7',
 '00ef59a43670dc2ae8edc383bcd52d97',
 '00f2f97f74e086e1f82acc285ee4a5c5',
 '01014f8d2c30a1fabc30f28e7de53467',
 '0101ad90f31ddb8fb24e9935a3dac9db',
 '0102f723b31790a32c35f877eb942bad',
 '0108949daa13dc94634a7d650a05c0bb',
 '010a3dbb67bc37800a041866844861b1',
 '011244ab511b20130d846f5f8f0c3866',
 '0114c5cd093c742334d5a5fa14140421',
 '011ae9520e81f1efe71c9d954ec07d09',
 '0128fe112c2ee94f8ec176109b6ca112',
 '0129a93b23aa71e7ea2b8b988d1c5287',
 '013893a5fa90241c65c3efcdbdd2cec1',
 '013e3ac3f5ed61cde07f8c54d02b01d0',
 '01415f1554556009b0eaf0ad7ca360bd',
 '014cca776c9bd5da35715042cdd002a0',
 '01546d3e6175ceaabd7d92f0c566579d',
 '01551a642641ce4371d7a400666afde1',
 '0162dad8330007f8f0daf43bcf4033f1',
 '017cd6c78e753ae58e1795fac350f321',
 '01815f05a4a4e424181a6d3be101dcd0',
 '0187da5fd71c7a2917346bf12a67bbe4',
 '018b348fd699821cdbc5bdc0b329982c',
 '018ea9aab6d856c9f9f299b11504de4e',
 '018ef9c5d5b20c5161a5c48703171c3b',
 '019456d451d855736ae5c32e2484a100',
 '019668dbdc511714d119c10b87dca089',
 '01a1e85c56486eccd29f3e824e745c2a',
 '01a318b645d42db0cdcaf9a0b7605723',
 '01a3c3d994d85ce5634d2d13c03fd4b0',
 '01a93e09220daa5b0316d426b701c76c',
 '01abaf7c7b831bba7403d08f56e58a94',
 '01b0069a8e0221a610294d4697b4abf9',
 '01b0510a8d3b0860429536653db5eb21',
 '01c2b9fcb0384c84648ed76c736552a8',
 '01c8d075b499b3079616e56503bf9168',
 '01c9bb647fc30bb3f2bf508bb2e7749c',
 '01d6446afde9fbf4332904bc331e9660',
 '01d74633de293c5790e191d6a544b130',
 '01e3254dd8d66c7d004775227bebc596',
 '01ee6e560f083255a630c41bba779405',
 '01f57c9a402a8b1ba7a654d7d13b55ce',
 '01f6f8d96b132d598e6ccfb6039c9902',
 '01fec681f2d698497151a88d6c5205a1',
 '0204800ac6954c809315ea6e1e6948fe',
 '020717d6ab0b440b37978d9bace9f9b2',
 '02079342f9e5f558b5351c222f6394b7',
 '0215ea0420992e458caa662118440fe2',
 '021a5634aba535a625ff8b1a6b51df64',
 '024ce202d752d81d45df640b67f51d5f',
 '024f9140bd829c346fc91fcf4009d251',
 '02502114299843075a27e4397b098e8a',
 '025534801b62d61f1c1c9e571ea74695',
 '02562eb68a9c682f5f644fa7a099733f',
 '0260e11ff2cdaf848530834b9cd00bc1',
 '0261c6d943d853dcc763eac39170d8e2',
 '0266a41a3b7d8870779c528a5b66615e',
 '02752dfc682a936280e042e038f8cf79',
 '027c56d37095bcc595ddd429f96902ae',
 '028abf6b0a4e96bcb62f4aeb126735dd',
 '02957c14fee52ac6d0617e6d86275a25',
 '02a4774868d677ef8ecff2168c0161c0',
 '02bdf8a32a04b542b18b937596f1b82d',
 '02c82f4c59af8bb89c0baca937b1b7da',
 '02cb781fd08fe2d7a6a56407daf2872b',
 '02cd1d17763c869ff3d4af5e28539456',
 '02f6df6f5c4666cdbfeae7901b913187',
 '02fb30c1dd4e6ba448c8bbe4685b77ae',
 '02fe3eea41166a1d3eb75307a12c4a63',
 '0302ee5d111875b1ed05dd6630404c6d',
 '031625d57b5e9a5c8bcd7b9a82246fcb',
 '031f23b4a8658fe9b4fc18007cc95851',
 '032111ac5bb2e0cbb9a22745a77eef8f',
 '0325dcb3ad5f33f107e850fcdd6e5b4f',
 '032993869b3b33cdc46ec374855c19a0',
 '0339aac16e3dd93ee397315a224147a6',
 '033bc3846ebbf668b702a5719f966fb5',
 '033d34dc31e0ee291d11af204c9376d5',
 '033dae57cec0aca171d47090f299bed2',
 '033e1637bed9b9f3dccac9c6c419adc2',
 '0343e7f7e9e4cc1ac974ab130d46eafa',
 '0344c63913224cf62e3d8bcd5dd93a9b',
 '034cf2b503a9a7efe404f000fb988534',
 '035480fbf46e946e21e7dce78637c329',
 '035b53e8aabf8763537a296c291135d1',
 '035dcbac2fa931002bde1f9853c4a30a',
 '036161ca6aa4daa43cc3bc55602e8960',
 '0369e9cbb6e58086d59ed621987b65d8',
 '036b9096b099f0f6c5611da078f73e43',
 '0370b082971fe47663fedaf76fa5e492',
 '03734851475ddbff6572830b84dcc761',
 '038a29d3e340d8ab60644826c14596db',
 '038a7c88fcd819549f430c1fd907658c',
 '0391d2388a2442f14d055d5089a747c6',
 '03957d68be8743b115c7b9a48efcca27',
 '039c6997248b3a6ba3c909af35fce0eb',
 '039d7ffa518b105dabbeca84d7b7753c',
 '03a6078c0c12fb076b50ae017e590e19',
 '03a66c919172a500cea51763d9a22f56',
 '03ac68dac6f0e4db18f2e74b3a2ae751',
 '03b6cf4974e7aa0a44ab5099afedec7d',
 '03cd593a310656563a5aa3886ff30380',
 '03dd99aa091caee7b0ce8efdf7f274d5',
 '03de7a52c6daf7b17cf84383debc2362',
 '03e6ecfa6f6fb33dfeac6ca4f9b459c9',
 '03ec9ca738f579b956cb4af13efa155a',
 '03f0bf0a7403c050a7ce574f98fd8ab6',
 '03f0e6bb0924540875b9ddd96705c184',
 '040c4603d394992e4809c06b5f1d90c8',
 '041081d11262c5f150e655f5e5ff0a2c',
 '0420bfcdd86ebbcd774d0cb7a087923c',
 '042239d11ff7f47f1170b67f1cb5349d',
 '0424e80c4f0cae6ea9e65efeed75d5d0',
 '04286f639e2e469cc758bcf58feb867e',
 '0428eb1ea4b373245cfc3934cde6d55a',
 '04494b3ea2a46c6204620592419352db',
 '044faebbc12b24b24f6e88abc95f4801',
 '0452ab5ee9d46606d5d6fbcf5a206eee',
 '0453de2faeb8d349af739a68d9dee1cb',
 '0459d43804df005b79d9b248690cf777',
 '045cf248fcf9ac153e3c9586d1c70229',
 '0466444c23edb8510c348ce84e570e94',
 '04717c6776396c84dd605d8889a635c5',
 '047182a6e86808669f896307dcd550c7',
 '04738c36453aa559b68043a2b2d00f7f',
 '0478932c2e3ef9f5492e38b52bfc5d94',
 '04994993c9e416f32ce24c7e7501d3be',
 '049a2b96bf575f6fad12b576d3aae44c',
 '049e258c0250ad270644ca9074cdbc5c',
 '04a01c0728db27ddb9d284ca99aac9a2',
 '04aeb7f7ca32c075b520c28583adabb2',
 '04aed38b30c4de9461c8a9940e99d811',
 '04bb8bd7ee6f88a16623fe5c6dd4da91',
 '04bf8b28859a541087d3186c932e27e6',
 '04c193ff7be9b8b895fa10e3a20bb6ad',
 '04d1f1f8f52b15520f5895be87884fbd',
 '04f2409cb10dda9e308d37ec4f889eb4',
 '04f3e0ba1b46a723e88d7331f5e21419',
 '04fd89a35648f61485c02b90454bf246',
 '0501d62912b9a6ff04eae4ffc56affc2',
 '0505b45c54f4bc77ecb22ffe71b29ed8',
 '05067a8b46cbf6e4cfa6080ee97ac981',
 '0506ee0b2a39c2caf6685ee72ebabb9e',
 '0508d7ea85ba9be425657cc04c24a4f8',
 '050d07286aa834740b535d3aea87e013',
 '051132a778e61a86eb147c7c6f564dfe',
 '0511640ec15281c29b396689471340dd',
 '0512ed00fe622b41f1959d354138f192',
 '051c2436c0acdb5e09d085c7e4a764f3',
 '051d112b55e4c9f9dfa53307cc2ffb62',
 '0533afec465c6a68efb7df00e5332b40',
 '053700069ddf3c4f1f6c477a48337836',
 '0551db8af443829de9cfc1770eb15977',
 '0555c4d61c2a897653377312f2c14b4f',
 '055859485d697b38ee46da1ab68e5f50',
 '0564bdb6bbd81f2315d29c96aad37958',
 '056c4d8c3a338b66ea0247bc5e0237c4',
 '0570e5d8e3e4532ca90597a979d1e7ff',
 '057c60e970f445a969dca914ab8d1b8e',
 '057fb23418bbab7f82689ab76a54cbac',
 '058714deae1e656a0632a9ed19e262b9',
 '0588c987e1c1919569c4bf005bdf7398',
 '058fab57c813368cb0e2fb91484d9ec6',
 '059412ad34b2c48179f178e3138b5022',
 '059bf541e8754826c52b7184a52f3446',
 '05a1b049aade6b9e9ce1209a31e62a5f',
 '05aae40e8904366f92a7f738d7533338',
 '05b13ce73a727aefbb323d543426fb9b',
 '05b42653897fa9739366a25612f1eb08',
 '05ba77b1cf87cd4597d988581f269b44',
 '05c9d4438807f4ecbbea5be0c60e6ec6',
 '05d1b84871feea216485eb3ad14633d8',
 '05d3315aef94ddf37fe9c4886816a702',
 '05d45c0a96b2c363f8b9a34a1f181c58',
 '05d676834dbed1639cb5eea70c1e307b',
 '05d92b99575f75e64e0c0e7293c13803',
 '05dc427060325263843c57a04aeee7ed',
 '05dfd35f424da60897dfafc2340e0891',
 '05e1efa511adb8c1e2631b13734031d1',
 '05e560d65da399f4310a51c5bc7f44d8',
 '05e64c5b1e5f246ae6e8bc109e557bf4',
 '05ebb3c5e091a8322a50672d478d117e',
 '05ee3741c4523f2265a0dc3c1b69d529',
 '05f202ee95a17a4b1e6dbe1916ffe8bf',
 '05f3c5986c9c49c6f04d4e15fa01a785',
 '05ffd2cd8b2bac6296b63f1085032419',
 '06014542a807dabcf30867a2414b5e83',
 '0615151ee49a727a15e49e8a531b47c3',
 '061fa33f6ba0028fbbad8caaeac8d145',
 '0622cd29e4e0e4f198abf15614819ae8',
 '06286730d9f827c188ce4af565f09c6a',
 '0647eec06157a83b524df13f045d1fd7',
 '065e7a6c7c848aa3f17ae034e7fbec23',
 '06632edb4a24bf2935ace8859d0134da',
 '0669fb9cad9677ae93402dd6ef07af3d',
 '066ca890a8f0511461d66d421e2ed2b9',
 '067ccf7d0633b171dfdbf57d19e77227',
 '067fbe5569cedead356fae1e77165b45',
 '0683913284e5859d1d2e3e9f01e07ceb',
 '0686521b0b8cf9426f253601b805fb52',
 '0690821a2e255ce175bfa7f36e308f63',
 '0697473448bb5e83ac926fe92271e7d8',
 '06a21aefd2f5e5ece6397e5fc10860b1',
 '06a8441fb50ec661dd4eff6e81099d5c',
 '06a99b2b11aa921a40c073a64c6ad395',
 '06b2f3ff0d667703ab66052b1616a302',
 '06b2ff94bd0270f543deb7074c2a006a',
 '06b805ae2b70b172add6df8dae94fff2',
 '06ba60d8ce256b3edecbb31323e37576',
 '06c4364c837021fda2868310025cbb4b',
 '06c585d390e6e6ddd213f2715c367601',
 '06c59659f6124062db8bda3d7ef038c3',
 '06c60e030c4216ce9ef5c2ba8db919f0',
 '06c69cf01de70640c23fddb47572b8dd',
 '06d84d5df2221f299b1405a63b6701f3',
 '06dfb2b996464c7b0e4c5177d433edbe',
 '06eda17e0e78b183fc71d46d32cefb5d',
 '06eefcf8135f5253c975adb82276ec6a',
 '06efcd37617307118fd48b3a493c133b',
 '06f3c1a8441d61da08aac07558ab5f05',
 '06f864ba601b64bf44c312b2e5cdd894',
 '06fb5119d9b405dc7f26140820025e73',
 '07011dce1196d722a672c30918252dea',
 '070d087c1badb18ee110e19cbe158a40',
 '070d372757bfbb0cee7d68fd50369fc4',
 '0713d4d16867ae5c5215b86cb76083fc',
 '071ff9c782ead87dfa9b1c025c25e769',
 '0721d587dd8b168403df0a9e5d6ab6ec',
 '073fb0068960013841ae6c7d28d9c803',
 '0740b2aadf9f282346e0d2142c619067',
 '0740b61521fae0508311c834d2e78875',
 '0742030431be6b6807b9ca0a7eefe127',
 '07494843e43e308ec5b7ec0e9f0ad829',
 '075eed8cc3d035092115398c521152ab',
 '0760a14308badcbd370c6866c9db3a0a',
 '0760fe6c93bbd24e53213405de113a76',
 '0768d99d77bf3a917fcf8069552508a1',
 '0769ec72a79dcc0ceffb4d418ee5d5e4',
 '07721069d7590cdac4891353316ed6c9',
 '0777120fdd60f6a3cf8eaf3b8cf3585a',
 '077c02e3854ba35e3279af36e518ff3c',
 '077c76dffde69c0b90c28d78ef2ac31e',
 '07854dd260192cc96748dd3bfd61d51e',
 '078b40b11842c2df626d71a60e971f1b',
 '078fc0b0a1eed8b7fd09eb6cbb5923e2',
 '07921fbf3cc8835a541e39173e918ce7',
 '0797fa5e2725c9b801e6d01cfa9a09da',
 '07a5129d03938c17811a621b5665bb04',
 '07a6d6a7b2a64306ac3544e7dd55c5e6',
 '07ab6d47d868962851d22d4d1249593d',
 '07ac9545dcc585901865f7f958a7857d',
 '07aee7de1f86a98ae6c3c7d5df60374c',
 '07b4b2f75dd4f9b0f9915d7063e798b8',
 '07bbac2eee5b459e894b2f20faf8e3df',
 '07c12d0f562f17579aabc18c11e2ad54',
 '07c3a06d3617ad26847c00aadf719eb5',
 '07c566b1b7520bbe9d785556872074cc',
 '07c9ba701fe26c4d6de66965e4d35157',
 '07cb6e153e67a71402250cafc92d3fe8',
 '07cd31eb3e596d7ebc51d920beccd76a',
 '07d161a3f322c9ea3cff9ed043349e4c',
 '07d23125c1d7e97a968cdbe97122d9b7',
 '07d82e7e5749cbc21633134f489a7fbf',
 '07db18d326b0d42688d2cd922a6e02e9',
 '07db76e6cc063ce8bb90de18216e8ccf',
 '07dead6ba9ef577c41b2ad5049f5e9cb',
 '07dfe44d410caed5497120ebef07b348',
 '07e5378ad3928091c08dded1f6b5353d',
 '07eb2311cb7791dc47b03edfb9c357d8',
 '07f9314c9eec5959eafb3c511ac97cc8',
 '0806c77b8d7f8577cd0af9613db9299c',
 '0812e5efe41ac63eb29583269843d8e2',
 '081d1700020b6bf0099f1e4d8aeec0f3',
 '081f985086b569c68f9a1fa0278187f4',
 '082155fdae6472bf90d0e0a70f83c744',
 '0839c18bb2ca5053a556c6008ba5ec79',
 '083a89dfc9a74a3f809035f886634ee2',
 '083eb3c3a0d02b6c3de4901d69e39b52',
 '08442bce192528f64b24ec9222f44044',
 '0844f274f2a388e70231d3133754ac35',
 '0850bf4d0056a34dc0ba6c1c63fc7d2e',
 '0853ab3a3dbadae1e6f28b933ddff809',
 '085924d80d57f282c294b8bd59cbd1e3',
 '086a51e48347510728864ffed276ec1f',
 '08745659f524c26b2a70536b3938bf09',
 '088006f2453c4183b1ef46fb607bc31c',
 '0885a49e00250499aa19b3f21be0904a',
 '088869b047b7336c8d31bea5cf10cf24',
 '0889de8637d252e22dd1ce522f5ea672',
 '088d83359d1a00ba24251220ace42edc',
 '088f38c1f4f9d953bd85bbc6fae73f67',
 '089107073978c064c53772de534abd1c',
 '08937602fb8e0a3e27a87844d1b126ff',
 '089a1c26766c10e2d8c4cdb86ed769dc',
 '08c182c884fec1fad1b1e4a19d482acf',
 '08ca5715d79a32bb574d28b34c0ed052',
 '08d0eab34ea5bab14e7e56dabafcdb7f',
 '08daf3cf9bcf3d306ad08dbb9a53f4f2',
 '08eae737d6de0db70d4bcb02b799cd02',
 '08f362b8c0da181ca414c58e52555c64',
 '08f4d0d827ef5216c35362812eeae644',
 '08f84015dd3811451c7a99f3357480be',
 '0900f93acb9f42caa354036b6453816d',
 '0905c0dc82fb8fe621c43f53719a55ca',
 '0906a09b04f8d82c2cad5b820602a403',
 '09125244cb0f0db65b66ce7f33fa02c8',
 '0924f6ef94d465be6a2ced6579726448',
 '092573182f723f671a3d4566ab052921',
 '092d380367a75cbbea280ef3d1f2c711',
 '092f49f51e7c90f0286baece053295a6',
 '09376dd7b6deaec0aaf1a2feb7833245',
 '093a21385d162d81f65583c0133ecf12',
 '093b519e943397a88b4067339ebffa5d',
 '093e0876aa291878d6725561b08addcc',
 '095c13d937c0dd9f547035344ba6c6c4',
 '096688dacee6b1a1a5660ad15024a6f9',
 '096f214b3f16d0d36d17a3cb128c19a7',
 '09790cae0f405ce0fe4b003dadfc18c7',
 '097a4ae17c881ac6a40d56d0c80e1a71',
 '097c63f9c6d46cfe5bd4937f277fbdbd',
 '0999a23a7982827edaf16f0244d2e2d7',
 '09a7d6ecaa44bfdb43371ad6f203ac93',
 '09afc85ef67340016e0c8a1c70163769',
 '09b3f58371e614ff88790458a010bb22',
 '09b9674023305cb9a0acb367600efffa',
 '09c83d8233d51cc43ac2af361e0662ae',
 '09c9887c189f99704b452f193a40eaf7',
 '09d0e96d821aa1a94c1c33f6325ed851',
 '09df460412ce705d0f634436f518f46d',
 '09e0a73c91c615581fe4097ce3ae2e09',
 '09e1e8ad685b4d843457c37fb071d3c9',
 '09ea9c40b1ee28b4712aec08f108a0c8',
 '09ee91a2120006e587d2e63c7bf0230f',
 '09f0b00bd079304f72c079d369925aee',
 '09fca09845746d28dcda4981a8632bd7',
 '09fcb37b4bf132c373ae0435f13fa059',
 '09ffc5c9e63ae4cbf70e31a5db164114',
 '0a072917005494298d153c01bbd8f689',
 '0a0ac65c40a9ac441651e4bfbde03c4e',
 '0a0b773c653cea6653a1e02faf1566a5',
 '0a114862f10f4021fa7fd916b93aea94',
 '0a1665762c67817e64f4cbee1c79b44f',
 '0a16dc6491142ff8c7c36f3b3f4ebd02',
 '0a18ba620458e09504405e6a0a79ce2e',
 '0a191458e89dd7016e2032e9898bb5f8',
 '0a1aef5326b7b24378c6692f7a454e52',
 '0a212b35778c1bce896d4574124c6441',
 '0a26a07d95ed851cdfc7f55f44e2ba77',
 '0a2a1f3849c4b41e6d6715bb919c158a',
 '0a2d01ecb9e01cf972c1e1d31ccacb98',
 '0a3022286196be410476be6b60733b43',
 '0a3b8d3f979c06dc7b8ff6cf1f9343e4',
 '0a411e44ec67f3d5d80a5b3d5a3edca3',
 '0a466b4369d04de6d5a339f57f605765',
 '0a4fbc9ade84a7abd1680eb8ba031a9d',
 '0a50d4ee79163edbf6f2d5c3082c2f51',
 '0a5da3b480ea895bafe976f54050c9f1',
 '0a678538e529b9f1089c47bb2ffcda9b',
 '0a695a94168b32705b91779586c6b2e7',
 '0a75c2f2e7bc1090077b8ef4aeeeacce',
 '0a7aec5bd4485a6f5b67e53a8636305c',
 '0a80df703ea62ce2c98aab7e6cd995c8',
 '0a8e6cb00c56ff52e3489ccd6305a758',
 '0a8e835f9864b88429863f285c11078d',
 '0a9304d103869d45553070a5717cf82f',
 '0a953437a2627f2080cc6c8c5939d59b',
 '0a9909b1cd924cd593151ba2d3d3dd55',
 '0aa04c0bff3f7c0d1bd97c41d0c14bd5',
 '0aa9ffc4b4bbe561e983be219497240b',
 '0ab8c789c5bd3e97a62507d760e02e90',
 '0abd4fc2425edd5c2efb2c149e9319c6',
 '0ac383fcdc6f1957b3ecceaf0acec909',
 '0acad710903d144db1ed35a1fee56993',
 '0ad8663c40dedf625c03ecc586af5c52',
 '0ad98c531de3616cc63a92d6cf871494',
 '0ada863fb878555ffd8dbd34e2496f76',
 '0ae12e31674667003309519e5f98304a',
 '0ae5b1fd17fa6ddd9cf61e774e8af122',
 '0ae620944412bde5a4698049c2bbd3af',
 '0ae8662d977c0bdcb68f704be748f065',
 '0aee36a63b071c37c1d647d931c7a833',
 '0b029c678b0391bea96cfcc7116b83a1',
 '0b02aeb680984f6bee2fbd517f1fa6d4',
 '0b0c71f182ad71d65d0425f6c9008f94',
 '0b0e106a53f9dc3b28a9b15f94510b7a',
 '0b0fa9da5382959b802284f725a2ce30',
 '0b11cf6759b6b31a11d71ad38ed4d3c5',
 '0b154484e0e38928fc1c0dbfda760ea6',
 '0b22826cc68b8d3177c5be2f4e1ae720',
 '0b357271846b8fc4d32dd774b74bf276',
 '0b36cce0b170c34b8c11fd15b42324b2',
 '0b3f09a003f9cbc1e8c54f230be2ba2d',
 '0b4729e08dbd4e916a32804f943853f2',
 '0b4bfa8697aa6c71b86ee112bd775b24',
 '0b5213c456c26b48ca011b9865c4e6ce',
 '0b5b42c2920b109c7c876c6ddfcf8df8',
 '0b5d222662dfa80d7ba8b101bb88e20c',
 '0b6006be69ea1764f9bf80e5091b1e8e',
 '0b78363604f4d81c3e27f90bd3066df6',
 '0b7995c5e532803dc1bd077eaa4d2a01',
 '0b805259394307f01adc87b57b704602',
 '0b80aaae33916b6c56b4308584cd67c0',
 '0b8c73a84bc8b5f1a11b27619c1bd8a3',
 '0b98b21145a9425bf3eeea4b0de425e7',
 '0b9dd99214ab1ef052cdfd62fdfe82c4',
 '0bb76fb5f7cfb1dd4c3760f7481a1d05',
 '0bd8e34912a6344fc3962b39d6e46a7e',
 '0bdadb23e846f9c247d3ea571f63913d',
 '0bdb1109dfa8f6f0f3a8c4fad249506c',
 '0be45114544283beb4f6d371f946e889',
 '0bed7f179df709d35aef763544ebfebf',
 '0bee0cde729de2d82b39527c37f11934',
 '0bef06d948ac1fe20ade505ba9960885',
 '0bf07e1bacd4a1c2c9b62960445fc0c6',
 '0bf74ccc6888feb5cc717241a5c826ce',
 '0c10e24ffcce63d46228582367bc1377',
 '0c11bc2eb3de5bd737ae186aea0d0306',
 '0c2079e62ddfb06a8a5300cefaa3a970',
 '0c285f4a92ac064b0fc85f3aa01e48f7',
 '0c2b96e2f30e34dd68b2075b83b0db25',
 '0c402b0f68dfb6cf6d8045526736d425',
 '0c4030b724bc12b38f4bbe54a3952056',
 '0c469843f3e05f73485ef54a73967a81',
 '0c5ef740a9befbf439439f0b8e652a0c',
 '0c636320c819477ec9fb4c221243b77b',
 '0c684171749ce2c0c601b9d69b882edb',
 '0c698358c936351c9a1dd79d3d89aabf',
 '0c6a7e3c733bd4f4d89443ca16615fc6',
 '0c75be7070d22662ecf98dda0ea724b5',
 '0c76c19b3f015e0387dd2adcbef86182',
 '0c7bf87c0c415d3226451214c5b382b1',
 '0c7d2e66dd63fca8b98c38146ba96f6c',
 '0c7ec6273560d99990a18daa57da8ed8',
 '0c7fd5b900fba01294ce9cf71d15ff9b',
 '0c8c247e84a3c4fe4d40846bdeac105f',
 '0ca39409412cb8e473da701a1418e4dc',
 '0ca78778307cacb62fc7d0d5f8ff579d',
 '0cb20ec518beba3ffe05c176cf2769d8',
 '0cb37232f9295c2876ee87e949d781e3',
 '0cb3915982ff4a65a1c52b89616d0f49',
 '0cb91b8fe14a6d51725371b1956750a0',
 '0cbe760fa8204491c0bfa5574da82b90',
 '0cc05d4528927f90e226a76844666c45',
 '0cc824d4b3896c3ee6b6f6c4a8cae900',
 '0ccbfd4abc669a79da23bcaed50cb7e7',
 '0cd0c34f2709f45839bb442655883dc4',
 '0cd291c189895fbdcc14f4d36e1abc81',
 '0cf6af447e4e8502ae9d0370c7edf918',
 '0cf83a19a8281e4a281dece9854008ac',
 '0cf8dd905fb4f2f876eb241bf67add40',
 '0cf9a5a8732ff379cff0ac1a1a54634b',
 '0cfa8fc7ad1a0f76901c761c7c108e22',
 '0d029f8b2f72732630d3d81bc0daac1f',
 '0d03df2e9ed557d0c9edcec777056c1f',
 '0d0a7a1b8c1495d66ac9c427a36d9f6f',
 '0d0e4dbe84356f8ec4a4ff7616b4850f',
 '0d266f5353352d86d3c092da96dc67f5',
 '0d26f6ebf87258f502f8fba529fe3079',
 '0d29c5718d65a853553e1a4190c85a68',
 '0d2e947bb475050c9039828b754ff6fa',
 '0d30dc1e0070e7a934f39452e3ad3b83',
 '0d31c772dcf5e2c8394099c0bcc20011',
 '0d35328406239f0b97cd410036d8046f',
 '0d3560aa72cf2176f272ae7ebe3c8bd6',
 '0d3965f7f328a308990e9a37eeee08fd',
 '0d3b1464574b7db3d664dc0aa0b66549',
 '0d40f562896c51b30af1949901fd2d69',
 '0d41f390aae11f5ed0ce8c1eadfebae3',
 '0d420cb872c8f385c119071c1302264d',
 '0d4c15118dc3c0c0f9fb402d15286089',
 '0d4e7a191d3824127b65425027827f33',
 '0d55ccb39234d5369ecd767186ef9127',
 '0d5b5d084d43bed385e4c41afc273f75',
 '0d6acec8422b6fb8e214f770a1ff7d2d',
 '0d713a8274dc92be9a75639d9b6558e1',
 '0d758802aeeebb56a0632f26285c3d29',
 '0d7ece5a693e80f4745a0750ec1f3cd1',
 '0d96a4bffbd85c60c4eec095f4c6d34b',
 '0db59846b8c385f7f0d8d1c084d3184e',
 '0db7b6f4d71850df763ae61eeee8ea31',
 '0db907ff35f16c60a0a4aeabea20dd63',
 '0dbdb924a9140849abd4ff650c5356da',
 '0dc7b1615100b4f5d3ae294bae0d5d43',
 '0dd1d5cdc448658c8be9d136eba8c666',
 '0dd8ef01229d7509562e1ef1dc92953b',
 '0dde4c1aab003e908ec917aabbd256d4',
 '0de9e6e651d4410d8730b5ab75c63289',
 '0def2b4c6eededaa53e20636c9ae3b76',
 '0df187b5072103a0919c1a34be03e7ed',
 '0e093fa90e5be5666cd396d722cc84ac',
 '0e117be65f091eef126fe3e5c68a187a',
 '0e130f7333967146f0d7bbd94a8ae047',
 '0e17c6df39f947b40b60d42c5dc68b71',
 '0e1cfc5b78d1a67bd41974ea2be8bc4c',
 '0e1db1a49e1775df6b9e971869600d9f',
 '0e21abbef40e569be72ab0ad90544f87',
 '0e34e49f693b5582914ab0a971a9e575',
 '0e49606d0861fc8c8d797efb580c32d0',
 '0e566069cb507a0581b54998b23e2ece',
 '0e5734a5483002be04b734d7c88058be',
 '0e6a918cc2a038ef1e8d3b0d9554f05e',
 '0e6a9e9f031fca5f634641fe41d31b24',
 '0e6af94d17007c94d858b3bb7adb7dac',
 '0e76073ded0ce6bfc5ecafea10b50d0b',
 '0e7dd1bdfcc28525205e0d01573fde8d',
 '0e81c45fe6e9da1d0bc282077f879b99',
 '0e8291c45a5ef61d2d9ecfcf3224899d',
 '0e86ebc2195ea6cb9733f1c95a86b012',
 '0e87195ff59d4294d61b8bffddb3c03c',

In [51]:
df = pd.read_csv("/data6/anushkapa_scratch/train.csv")
#df.columns = ['image_name', '0','1','2','3','4','5','6','7','8','9','10','11','12','13','14']
df

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max
0,50a418190bc3fb1ef1633bf9678929b3,No finding,14,R11,NaN,NaN,NaN,NaN
1,21a10246a5ec7af151081d0cd6d65dc9,No finding,14,R7,NaN,NaN,NaN,NaN
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,3,R10,691.0,1375.0,1653.0,1831.0
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,0,R10,1264.0,743.0,1611.0,1019.0
4,063319de25ce7edb9b1c6b8881290140,No finding,14,R10,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
67909,936fd5cff1c058d39817a08f58b72cae,No finding,14,R1,NaN,NaN,NaN,NaN
67910,ca7e72954550eeb610fe22bf0244b7fa,No finding,14,R1,NaN,NaN,NaN,NaN
67911,aa17d5312a0fb4a2939436abca7f9579,No finding,14,R8,NaN,NaN,NaN,NaN
67912,4b56bc6d22b192f075f13231419dfcc8,Cardiomegaly,3,R8,771.0,979.0,1680.0,1311.0
67913,5e272e3adbdaafb07a7e84a9e62b1a4c,No finding,14,R16,NaN,NaN,NaN,NaN

In [46]:
r = df[df['image_id'] == a]
r

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max
689,000434271f63a053c4128a0ba6352c7f,No finding,14,R6,NaN,NaN,NaN,NaN
56742,000434271f63a053c4128a0ba6352c7f,No finding,14,R2,NaN,NaN,NaN,NaN
65515,000434271f63a053c4128a0ba6352c7f,No finding,14,R3,NaN,NaN,NaN,NaN

In [52]:
#create a new df with the images that are in the files list

filtered_df = df[df['image_id'].isin(files)]

In [53]:
filtered_df

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max
0,50a418190bc3fb1ef1633bf9678929b3,No finding,14,R11,NaN,NaN,NaN,NaN
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,3,R10,691.0,1375.0,1653.0,1831.0
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,0,R10,1264.0,743.0,1611.0,1019.0
5,1c32170b4af4ce1a3030eb8167753b06,Pleural thickening,11,R9,627.0,357.0,947.0,433.0
7,47ed17dcb2cbeec15182ed335a8b5a9e,Nodule/Mass,8,R9,557.0,2352.0,675.0,2484.0
...,...,...,...,...,...,...,...,...
67905,955f258cc29153f996ee6716218c1196,No finding,14,R8,NaN,NaN,NaN,NaN
67906,26d1d5a0ef2e692c6340e74859ffdc53,Pulmonary fibrosis,13,R10,1163.0,787.0,1338.0,941.0
67908,db169d0be36123bd55b866d6aa73983b,Other lesion,9,R8,6.0,670.0,272.0,1736.0
67910,ca7e72954550eeb610fe22bf0244b7fa,No finding,14,R1,NaN,NaN,NaN,NaN
67911,aa17d5312a0fb4a2939436abca7f9579,No finding,14,R8,NaN,NaN,NaN,NaN

In [54]:
filtered_df.to_csv('vindr_val.csv', index=False)